### ISSUE TITLE
Question: DNN Rule Extraction Study focusing on Alpha Fold

### ISSUE THREAD

**Issue by HalitTalha** [deepmind/deepmind-research#167]
Hi there,

I'm not sure if raising an issue here is the best way to reach out for my question but here it is:
I'm planning to do a research on NN rule extraction focusing Alpha Fold's performance on CASP13 dataset.
Briefly speaking, I just want to know what would you think of such a study? Maybe DeepMind has something similar going on? Any response is appreciated. 

Thanks in advance. Regards.

**Comment by Augustin-Zidek** [comment]
Hi,

we are not planing to do such analysis on the CASP13 distogram neural network since AlphaFold 1 (used in CASP13) has been superseded by AlphaFold 2 (used in CASP14).

However, the distogram neural network behaviour analysis might be relevant to the study you are proposing: It is included in the AlphaFold Nature paper (https://rdcu.be/b0mtx), see “Interpretation of distogram neural network” in the Methods section and extended data figures 9 and 10.

**Comment by HalitTalha** [comment]
Excuse my ignorance, is AlphaFold 2 open-source?

**Comment by Augustin-Zidek** [comment]
No it isn't -- we are working on a paper on AlphaFold 2.
