### ISSUE TITLE
alphafold feature generation

### ISSUE THREAD

**Issue by luwei0917** [deepmind/deepmind-research#18]
Hello, 
I'm interested in the details about feature generation described in the method section of the paper.  Is there a plan to open source the script for generating the features from MSA data? or is it already exist, just that I didn't see it. 

Thanks!

**Comment by Augustin-Zidek** [comment]
Sorry, there is currently no plan to open source the feature generation code. (It's tightly coupled to our internal infrastructure as well as external tools which we cannot open source.)

However, I updated the [README](https://github.com/deepmind/deepmind-research/tree/master/alphafold_casp13) with descriptions of all the features. I also added code snippets that show how to calculate most of the features that are needed. I hope this helps.

**Comment by kad-ecoli** [comment]
Why the pseudolikelihood estimation parameters have 484 (=22*22) parameters instead of 441 (=21*21) parameters? Almost all potts model implementation only has 441 parameters for each residue pair. Is it possible to release AlphaFold's pseudolikelihood estimation pipeline?

**Comment by huhlim** [comment]
I guess they used 20 amino acid types + X + gap.

**Comment by huhlim** [comment]
Thank you for sharing some code snippets for the input feature generation.
I found that "deletion_probability" is somehow weird. According to A3M format (https://github.com/soedinglab/hh-suite/wiki#the-same-alignment-in-a3m),
deletion cannot be mapped to the query sequence. For example,
a MSA in FASTA format,
```
>Query
ACDEFG--HIK
>Templ_1
ACD--GYWHI-
>Templ_2
ACDEFGFWH-K
```
can be converted into A3M format (by using HHsuite reformat.pl)  as
```
>Query
ACDEFGHIK
>Templ_1
ACD--GywHI-
>Templ_2
ACDEFGfwH-K
```
Since those deletions in Templ_1 (yw) and Template_2 (fw) are aligned(?) to the gaps in the Query sequence, the deletions would not be counted.
