### ISSUE TITLE
Alphafold-casp13 input data question

### ISSUE THREAD

**Issue by Planet-KIM** [deepmind/deepmind-research#184]
- How can I get the .tfrec files from the pdb file?
- I want to get tfrec file.(on pdb file)
- Please give me solutions.

**Comment by Augustin-Zidek** [comment]
I recommend using some of the open-source implementations of the data pipeline, see e.g. https://github.com/deepmind/deepmind-research/issues/28 -- using the `feature.sh` script from https://github.com/Urinx/alphafold_pytorch to convert the input fasta to the tfrec format.

Note also that this repository contains only the inference code (not the training code), hence there is no need to run this on PDB files since they already have atom coordinates in them.
