### ISSUE TITLE
tensorflow version<2？

### ISSUE THREAD

**Issue by Rashfu** [deepmind/deepmind-research#246]
When I try to use the code of `Learning to Simulate Complex Physics with Graph Networks`, I use
```
pip install -r learning_to_simulate/requirements.txt
```
But the terminal shows that
```
ERROR: No matching distribution found for tensorflow<2,>=1.5
```
Is the code OK for tensorflow>=2?

**Comment by mmichelis** [comment]
I ran into the same issue, but it was because I used Python 3.8.8, using Python 3.6 instead allowed Tensorflow to be properly installed. But I had some trouble with pip in virtualenv and Ubuntu 20.04, so a possible workaround is using Anaconda instead with Python 3.6. After creating and activating the conda environment, install the requirements with pip. Then, all you need to do is setting:

`conda env config vars set PYTHONPATH=/path/to/deepmind-research/"`

and the examples should run as described. I think the difference between Tensorflow 1 and 2 is quite big, so it might not work out-of-the-box with the newer version.

**Comment by Rashfu** [comment]
> I ran into the same issue, but it was because I used Python 3.8.8, using Python 3.6 instead allowed Tensorflow to be properly installed. But I had some trouble with pip in virtualenv and Ubuntu 20.04, so a possible workaround is using Anaconda instead with Python 3.6. After creating and activating the conda environment, install the requirements with pip. Then, all you need to do is setting:
> 
> `conda env config vars set PYTHONPATH=/path/to/deepmind-research/"`
> 
> and the examples should run as described. I think the difference between Tensorflow 1 and 2 is quite big, so it might not work out-of-the-box with the newer version.

Hi, @mmichelis :
Thank you for discussion. The official code only supports Tensorflow1, so python<=3.7 could be ok for that.  I use the RTX3090 which doesn't match the cuda version demand for Tensorflow1, so I could only train the model on CPU which is much more slow and could get the performance as the examples show. However, I will change a computer to test.

**Comment by junhua-zhang** [comment]
upgrade pip, then tensorflow1.5 can be installed through pip

**Comment by alvarosg** [comment]
Thanks for the replies, the code is not indeed compatible with TF2, because it uses Sonnet 1, which is not compatible with TF1 compatibility mode of TF2. As a result it requires running with Python <= 3.6
