### ISSUE TITLE
Perceiver IO: Question: Optical Flow FLOW_SCALE_FACTOR

### ISSUE THREAD

**Issue by JOBR0** [deepmind/deepmind-research#266]
Hi,
could you maybe explain the reason for multiplying the optical flow output of the receiver by a FLOW_SCALE_FACTOR?
The FLOW_SCALE_FACTOR is 20 and there is also this rescale_factor (100) in the FlowDecoder by which the output is divided. 
So the perceiver output is effectively multiplied by  FLOW_SCALE_FACTOR/rescale_factor = 0.2 which forces the perceiver to output a flow 5 times the scale of the ground truth flow. 
I saw a similar factor in the flowNet implementation, however there the factor is greater than 1 to make the network output smaller values in order to stabilize the training.
Thanks

**Comment by cdoersch** [comment]
Greetings @JOBR0 ,

You're right that the code for scaling the output is strange and a bit difficult to follow; sorry about that.  Your interpretation is overall correct.  FLOW_SCALE_FACTOR=20 is something we inherited from the Autoflow codebase, and we kept it in order to reuse their evaluation code with as few modifications as possible.  Note that, following the training of RAFT by the Autoflow authors, the optical flow targets we used from the Autoflow dataset are also scaled down by FLOW_SCALE_FACTOR, and this scaling is undone at eval time by multiplying by FLOW_SCALE_FACTOR.

Regarding rescale_factor, we found during our initial experiments that downscaling the perceiver output by a factor of 100 during training led to more stable training.  The reason for this is somewhat unclear, but one hypothesis is that early in training, feeding the high-variance random perceiver outputs that result from random initializiation makes the initial loss values very high.  The network responds to this by learning to ignore the input so that it can reliably out 0 (which is the minimum possible loss while ignoring the pixels). This can potentially put the whole network into a saddle point.  Downscaling at the output layer results in small loss values initially, which can help keep the network weights well-conditioned until the network finds some signal.  

However, we found these constants before we discovered that we could use a curriculum with inverse flow examples to greatly improve early training (see our appendix).  We never re-tuned these constants afterward, so it's entirely possible that all this rescaling is no longer necessary.
