### ISSUE TITLE
Perceiver IO Training Acc Log on ImageNet

### ISSUE THREAD

**Issue by ShoufaChen** [deepmind/deepmind-research#273]
Hi,

Thanks for your great work.

May I ask do you have a plan to share the training log of Perceiver IO on ImageNet?

**Comment by djaegle** [comment]
Hi, we don't have plans to release the training logs. They don't show anything unusual in our experience: training and evaluation accuracy typically increase monotonically through training with a plateau towards the end of the constant phase of the learning rate schedule that precedes the cosine decay. Evaluation accuracy is typically much higher than training accuracy because of the augmentation.

**Comment by ShoufaChen** [comment]
Thanks for your reply.
