### ISSUE TITLE
AlphaFold: Usage for single sequence?

### ISSUE THREAD

**Issue by bluevex** [deepmind/deepmind-research#28]
As AlphaFold is intended to predict structure from a sequence, I want to input [some sequence of letters denoting an arbitrary amino acid sequence], and receive [a PDB file of the predicted structure(s)] as output. Can some part of the released code do this, using the released precomputed features? It is unclear from the readme how to use this code beyond replicating the CASP13 results.

For example, this modelling server does exactly that, but by method of comparing sequence similarity to existing homology models:
https://gomodo.grs.kfa-juelich.de/php/begin.php

I was told to post this here by the maintainer.

**Comment by huhlim** [comment]
DeepMind team only shared the AlphaFold deep learning model instead of the full pipeline for model building, so there are many features are missing including input feature generation and 3D structure generation. 
If you want to build a model for your protein, you still can try typical structure prediction servers such as I-TASSER, RaptorX, and so on. They are also pretty good. In addition, some of the servers (i.e., RaptorX-Contact) have their own contact/distance prediction methods and use them to build 3D models. 
If your protein sequence has close homologs with known structures, then it would be better to use template-based modeling. CASP targets usually deal with hard cases, which do not have known homolog structures or have very distant homolog structures. So, for a typical structure prediction circumstance, I hope template-based modeling would be enough to get an accurate 3D model. (I do believe that classical approaches are still better on these relatively easy cases.)

**Comment by Kohze** [comment]
I think we should give it a try even though google is not releasing all the code yet. Many research projects would profit from it.

**Comment by Augustin-Zidek** [comment]
As discussed in [issue #18](https://github.com/deepmind/deepmind-research/issues/18) the released code does not include Multiple Sequence Alignment (MSA) and feature computation for arbitrary sequences, though there we give some guide as to the features used for those accustomed to computing them.

But note that in any case the AlphaFold system does not use homologous structures (templates) it is focused on "Free Modelling".

**Comment by pentadotddot** [comment]
Hi, here I have found a reimplementation of alphafold in pytorch: https://github.com/Urinx/alphafold_pytorch

Here the author provided almost all the rest of the pipeline including feature generation.

Still I could not figure out how it works, but seems one can figure out something from it:)
