### ISSUE TITLE
questions about OGB-LSC PCQM4M

### ISSUE THREAD

**Issue by limei0307** [deepmind/deepmind-research#292]
Hi, @alvarosg 

I have some questions about the OGB-LSC PCQM4M code. 

In the [kddcup report](https://arxiv.org/pdf/2107.09422.pdf), you mentioned conformer model and non-conformer model. 

For the non-conformer model, "In the case of the flat input features, we have deployed a Noisy Nodes objective on both atom types and bond types".

For the conformer model, "When conformers or displacements are available, a richer class of denoising objectives may be imposed on the GNN. Namely, it is possible to perturb the individual nodes’ coordinates slightly, and then require the network to reconstruct the original displacement and/or distances".

I only noticed some node/edge_auxiliary_loss for the one_hots_features in the code, but didn't find Noisy Nodes on the displacements. Could you point out how to use Noisy Nodes in the conformer model? Thank you very much!

Thanks!

**Comment by alvarosg** [comment]
Thank you for the message.

> When conformers or displacements are available, a richer class of denoising objectives may be imposed on the GNN. Namely, it is possible to perturb the individual nodes’ coordinates slightly, and then require the network to reconstruct the original displacement and/or distances.

We mentioned this as a possibility because [Godwin et al., 2021] actually adds additional positional denoising objectives only to the positions, but not to other features. For the competition, because the non-conformer model did not have input positions, and we wanted to keep the conformer and non-conformer model as close as possible, we only added denoising objectives to the atom and bond properties, but not to the conformer positions. So when we say:

> Our preliminary results indicate a similar trend on the PCQM4M dataset.

we mean that the advantages achieved by NoisyNodes in general (rather than NoisyNodes applied to positions specifically), seem to give similar advantages to those find in [Godwin et al., 2021].

Thank you for pointing this out and sorry for the confusion!
