### ISSUE TITLE
DM21 density functional approximation in PySCF for periodic systems

### ISSUE THREAD

**Issue by JFurness1** [deepmind/deepmind-research#324]
I'm interested in running DM21 for some simple periodic systems. Initially some elemental transition metals. It seems the code is currently limited to Gamma point only calculations, which might limit me in the long run, but I'd still like to understand how far I can go with it regardless.

I have successfully installed DM21 and have reproduced the simple methane calculation from the README.md, so it seems everything is configured.

I'm hitting some problems trying to extend this to a periodic system.

Taking a simple hydrogen chain lattice I have the PySCF script:

```python
import density_functional_approximation_dm21 as dm21
from pyscf.pbc import gto, scf, dft
import numpy as np

cell = gto.Cell()
cell.atom = '''H  0 0 0; H  1 1 1'''
cell.basis = 'gth-dzvp'
cell.pseudo = 'gth-pade'
cell.a = np.eye(3)*2.0
cell.build()

kmf = dft.RKS(cell)
kmf._numint = dm21.NeuralNumInt(dm21.Functional.DM21)

kmf.kernel()
```

This fails with the error:

```
  File "/home/jfurness/anaconda3/envs/dm21/lib/python3.9/site-packages/pyscf/dft/numint.py", line 2027, in _gen_rho_evaluator
    if not hermi:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Is there any advice for using DM21 with periodic systems?

**Comment by jsspencer** [comment]
`dm21.NeuralNumInt` is only compatible with molecular systems. The PySCF `NumInt` class for periodic systems has a different interface. As arguments are passed by position rather than keyword (e.g. in https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/dft/rks.py#L92), this results in the kind of error you're seeing.

It should not be too hard write a similar `NeuralNumInt` interface for periodic systems -- only `block_loop`, `nr_rks`, and `nr_uks` would need to change (I think), and all they do is cache a few variables we need access to when evaluating the functional and then forward the call to the parent class.

However, the local Hartree-Fock features also need to be computed using the appropriate periodic potential.

**Comment by JFurness1** [comment]
Thanks for the information. Re-reading your excellent paper I see that the hydrogen chains you ran were finite. Previously I had jumped to the conclusion it was an infinite hydrogen chain, and that simple extended systems were already possible.

It seems like the plumbing would be relatively straight forwards then, but I expect implementation of local exact exchange for PBC would be quite an involved bit of work?

**Comment by jsspencer** [comment]
Yes, that's probably a reasonable assessment.
