### ISSUE TITLE
Any exemple for DM21m, DM21mc DM21mu ...?

### ISSUE THREAD

**Issue by johTin** [deepmind/deepmind-research#340]
Hi every one
I look for an script exemple how to use the functionnal DM21m, DM21mc DM21mu ?
Thanks

**Comment by jsspencer** [comment]
Use `dm21.Functional.DM21m` (or `dm21.Functional.DM21mc` etc) instead of `dm21.Functional.DM21` when constructing the `NeuralNumInt` object. The list of functionals is given in [neural_numint.py](https://github.com/deepmind/deepmind-research/blob/master/density_functional_approximation_dm21/density_functional_approximation_dm21/neural_numint.py#L38). A little more detail around this is given in the README, [just after the first example](https://github.com/deepmind/deepmind-research/blob/master/density_functional_approximation_dm21/README.md?plain=1#L115). For example:

```
import density_functional_approximation_dm21 as dm21
from pyscf import gto
from pyscf import dft
# Create the molecule of interest and select the basis set.
mol = gto.Mole()
mol.atom = 'Ne 0.0 0.0 0.0'
mol.basis = 'cc-pVDZ'
mol.build()
# Create a DFT solver and insert the DM21 functional into the solver.
mf = dft.RKS(mol)
mf._numint = dm21.NeuralNumInt(dm21.Functional.DM21m)
# Run the DFT calculation.
mf.kernel()
```

**Comment by johTin** [comment]
thank you for the answer.
I saw that there are no other datasets used with the functionnal ..
in figure S2 of the article (supplementary materials) there are other datasets used I thought it was with the functionnal  ones, I was a little confused on that.
