### ISSUE TITLE
Instructions to use DM21 from C++ don't work for me

### ISSUE THREAD

**Issue by PabloAMC** [deepmind/deepmind-research#391]
Hi!
I'm having some trouble with the instructions to use [DM21](https://github.com/deepmind/deepmind-research/tree/master/density_functional_approximation_dm21) from C++. In particular, the instruction
```
pip install -r requirements_aot_compilation.txt
```
gives me a compilation error
```
clang: build/src.macosx-12-x86_64-3.10/numpy/core/src/umath/matmul.c
      error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-12-x86_64-3.10/numpy/core/src/umath -Ibuild/src.macosx-12-x86_64-3.10/numpy/core/src/npymath -Ibuild/src.macosx-12-x86_64-3.10/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-12-x86_64-3.10/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/pablo_1/venv/DM21/include -I/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Ibuild/src.macosx-12-x86_64-3.10/numpy/core/src/common -Ibuild/src.macosx-12-x86_64-3.10/numpy/core/src/npymath -c build/src.macosx-12-x86_64-3.10/numpy/core/src/multiarray/scalartypes.c -o build/temp.macosx-12-x86_64-3.10/build/src.macosx-12-x86_64-3.10/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.macosx-12-x86_64-3.10/build/src.macosx-12-x86_64-3.10/numpy/core/src/multiarray/scalartypes.o.d -msse3 -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```
while 
```
bazel run --experimental_repo_remote_exec :run_dm21_aot_compiled_example
```
returns
```
INFO: Reading rc options for 'run' from /Users/pablo_1/Developer/deepmind-research/density_functional_approximation_dm21/.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2
ERROR: --noincompatible_prohibit_aapt1 :: Unrecognized option: --noincompatible_prohibit_aapt1
```
I am running this on a 2016 intel macOS Monterrey, in case that's important. And I also followed the git installation instructions.

**Comment by jsspencer** [comment]
What python version are you using? I suspect 3.10, for which there isn't an official numpy binary for the version specified in `requirements.txt` and `requirements_aot_compilation.txt`. `pip` then attempts to compile numpy from scratch, which fails (presumably because you're missing some dependency). Either resolve this or update/relax the versions in the requirements files so pip installs precompiled binaries.

Note bazel compilation also requires numpy to be installable, so you will eventually hit the same problem there. However, there seems to be some backwards-incompatible changes to bazel which you're hitting first.

We'll try to push fixes for both of these soon.

**Comment by PabloAMC** [comment]
Hey @jsspencer you're right that it was python 3.10. I have actually found a workaround that will not require me to further use DM21 from C++, but I guess an easy solution would be to make the environment have python 3.9.

**Comment by peverati** [comment]
Trying to bump this, since I'm having the same issue. It would be good to implement this functional in other quantum chemistry software, but at the moment it's impossible... 

I have also MacOS 13.0.1. Same issues as explained above.
I also tried on Ubuntu 18.1 but bazel failed with:

`ERROR: --noincompatible_prohibit_aapt1 :: Unrecognized option: --noincompatible_prohibit_aapt1`

removing the flag from .bazelrc gets me a little further down but then it crashes at:

`ERROR: no such package '@external_py_deps//': rules_python failed: Collecting absl-py==0.13.0`

**Comment by jsspencer** [comment]
It should be possible to build using the same version of tensorflow and (quite important) bazel 4; looks like there's a behaviour change in later versions of bazel. This is tricky to do -- it is easier to update the build to use tensorflow 2.11 and bazel 5.3. We've just pushed fixes for this.

(As an aside, it is also possible to compile using `saved_model_cli` installed as part of tensorflow with `pip install tensorflow`, and so avoid building with bazel. This also requires compiling the tensorflow XLA runtime library, which is located within the tensorflow directory within the virtualenv and the instructions for doing so are less portable.)
