### ISSUE TITLE
wrong package in requirements.txt, missing aqs-data and improvement of tests 

### ISSUE THREAD

**Issue by stefanhiemer** [deepmind/deepmind-research#49]
Hi everyone,

pkg-resources==0.0.0 can be found in the reuqirements.txt and causes an error when using pip install. According to this 

https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command 

this package does not exist and is a bug stemming from the operating system. 
Also, I could not find the data of the athermal quasistatic simulations in the bucket. Could you please upload this?
When doing the tests and some fail or are skipped, there is no message indicating which test failed and what the implications are. 

Regards
Stefan Hiemer

**Comment by vcbapst** [comment]
Dear Stefan, 

Thank you for your interest in our work. There was indeed an issue with the requirements which will be fixed in an upcoming push.
I am not sure what you mean with the tests but this issue may be relevant https://github.com/bazelbuild/bazel/issues/190 ?

Regarding the AQS simulations, we did not provide them on our public repository because they are easy to obtain from the equilibrated configurations. However we can convert the remaining data into the pickle data-format and provide it, if this is helpful for your research. Please contact us directly by email if that is the case.

**Comment by stefanhiemer** [comment]
Hi there,

I'll have a look at the link you posted. Thanks

Regards
Stefan
