### ISSUE TITLE
Why am I there so many errors? I can't even run the run_eval without running into all these issues

### ISSUE THREAD

**Issue by Mwape1997** [deepmind/deepmind-research#50]
![image](https://user-images.githubusercontent.com/32986641/81975575-8c4d7980-9627-11ea-9cd5-a0f0800308f3.png)
![image](https://user-images.githubusercontent.com/32986641/81975829-e77f6c00-9627-11ea-9181-c4856657f6bc.png)
![image](https://user-images.githubusercontent.com/32986641/81976741-4a253780-9629-11ea-9858-b3f7b1b5417d.png)

**Comment by Augustin-Zidek** [comment]
I think the issue is that you are running the script under Windows and Windows doesn't like the paths we construct in the `run_eval.sh` script. You could try changing the paths in the script to be valid Windows paths, i.e. change the slashes (`/`) in the paths to back-slashes (`\`).

Alternatively, try running the script under Linux or in a Linux virtual machine.

**Comment by Augustin-Zidek** [comment]
Did you manage to resolve it? Could I close this issue?

**Comment by Mwape1997** [comment]
Yup!
