### ISSUE TITLE
Datasets about Graph Matching Network

### ISSUE THREAD

**Issue by psp3dcg** [deepmind/deepmind-research#7]
Hello, Diego, thanks for releasing the code of GMN! I find the dataset used in code is generated by networkx, which is simple to control the similarity of a pair or triplet of graphs. However, how to compute ground truth similarity of graphs in the other datasets used in paper, such as the control-flow graphs and COIL-DEL? Further more, I notice that the graph pair in GMN is given a similarity label(positive/negative) as ground truth, so how to transfer graph similarity value into label, is there a threshold to determine the graph pair is similar or not? I would appreciate it if you could answer my question. Best wishes~ :)

**Comment by yujiali** [comment]
We have more detailed description about the data we used in the paper.

For the control-flow graphs, we compile source code, e.g. a function using different compilers / compiler options to get a set of different binaries.  The binaries corresponding to the same function are labeled as positive (similar), and binaries associated with different functions are labeled as negative (not similar).  For COIL-DEL objects within the same class are labeled as similar, otherwise not similar.

In general, if you have a similarity value, instead of a binary label, you have a few different options (these are beyond the scope of our paper, and are purely suggestions): (1) use the similarity value to get binary labels, for example by applying a threshold on it to get pairs; or (2) if you want to do triplet training, then if the similarity value between A and B are larger than A and C then (A,B) is positive in the triplet, and (A, C) is negative; (3) potentially even better, you could change the loss to make this more of a regression problem to fully utilize the similarity values you have.

**Comment by diegolascasas** [comment]
Closing this issue, feel free to reopen it if you have further questions.

**Comment by RZZBlackMagic** [comment]
@psp3dcg hello, I would like learn GMN, Is there a public data set for this project?  If not, Could you tell me the format of the dataset?
Thanks
Best wishes
